In [26]:
import pandas as pd 
import numpy as np

df = pd.read_csv("../data/crop_yield.csv")
df.head()

                    State_Name District_Name  Crop_Year       Season  ... Humidity  Soil_Moisture    Area  Production
0  Andaman and Nicobar Islands      NICOBARS       2000  Kharif       ...       35             45  1254.0      2000.0
1  Andaman and Nicobar Islands      NICOBARS       2000  Kharif       ...       40             46     2.0         1.0
2  Andaman and Nicobar Islands      NICOBARS       2000  Kharif       ...       41             50   102.0       321.0
3  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year   ...       42             55   176.0       641.0
4  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year   ...       40             54   720.0       165.0

[5 rows x 10 columns]

In [27]:
df.tail()

         State_Name   District_Name  Crop_Year       Season  ... Humidity  Soil_Moisture    Area  Production
49994  Chhattisgarh  JANJGIR-CHAMPA       2006  Kharif       ...       35             45    27.0         7.0
49995  Chhattisgarh  JANJGIR-CHAMPA       2006  Kharif       ...       40             46    27.0        32.0
49996  Chhattisgarh  JANJGIR-CHAMPA       2006  Kharif       ...       41             50   450.0       213.0
49997  Chhattisgarh  JANJGIR-CHAMPA       2006  Kharif       ...       42             55  1778.0       309.0
49998  Chhattisgarh  JANJGIR-CHAMPA       2006  Rabi         ...       40             54   216.0       194.0

[5 rows x 10 columns]

In [28]:
df.shape

(49999, 10)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49999 entries, 0 to 49998
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   State_Name     49999 non-null  object
 1   District_Name  49999 non-null  object
 2   Crop_Year      49999 non-null  int64
 3   Season         49999 non-null  object
 4   Crop           49999 non-null  object
 5   Temperature    49999 non-null  int64
 6   Humidity       49999 non-null  int64
 7   Soil_Moisture  49999 non-null  int64
 8   Area           49999 non-null  float64
 9   Production     49784 non-null  float64
dtypes: float64(2), int64(4), object(4)
memory usage: 3.8+ MB

In [30]:
df.isnull().sum()

State_Name         0
District_Name      0
Crop_Year          0
Season             0
Crop               0
Temperature        0
Humidity           0
Soil_Moisture      0
Area               0
Production       215
dtype: int64

In [31]:
set(df["Season"])

{'Autumn     ',
 'Kharif     ',
 'Rabi       ',
 'Summer     ',
 'Whole Year ',
 'Winter     '}

In [32]:
set(df["State_Name"])

{'Andaman and Nicobar Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh'}

In [39]:
#Chandigarh is not a state he is a capital  of panjab so replace Chandigarh -> panjab 
df["State_Name"] = df["State_Name"].replace({"Chandigarh":"Punjab"})

In [41]:
print("Chandigarh" in df.values)  # Should return False

False

In [42]:
print("Punjab" in df.values)  # Should return True

True

In [43]:
df[df["State_Name"]=="Punjab"]

      State_Name District_Name  Crop_Year       Season  ... Humidity  Soil_Moisture   Area  Production
45890     Punjab    CHANDIGARH       1998  Kharif       ...       45             52    8.0         8.0
45891     Punjab    CHANDIGARH       1998  Kharif       ...       55             62  380.0      1330.0
45892     Punjab    CHANDIGARH       1998  Kharif       ...       50             59    3.0         3.0
45893     Punjab    CHANDIGARH       1998  Kharif       ...       55             55  120.0       360.0
45894     Punjab    CHANDIGARH       1998  Kharif       ...       35             45   12.0        10.0
...          ...           ...        ...          ...  ...      ...            ...    ...         ...
45975     Punjab    CHANDIGARH       2010  Kharif       ...       35             45   25.0        55.0
45976     Punjab    CHANDIGARH       2010  Kharif       ...       40             46   20.0       103.0
45977     Punjab    CHANDIGARH       2010  Rabi         ...       41             50  600.0      2715.0
45978     Punjab    CHANDIGARH       2010  Whole Year   ...       42             55    3.0        56.0
45979     Punjab    CHANDIGARH       2010  Whole Year   ...       40             54    9.0       180.0

[90 rows x 10 columns]

In [44]:
set(df["State_Name"])

{'Andaman and Nicobar Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chhattisgarh',
 'Punjab'}

In [52]:
df.groupby("State_Name")["District_Name"].nunique()

State_Name
Andaman and Nicobar Islands     3
Andhra Pradesh                 13
Arunachal Pradesh              18
Assam                          27
Bihar                          38
Chhattisgarh                   12
Punjab                          1
Name: District_Name, dtype: int64

In [66]:
df.loc[df["State_Name"]=="Bihar",["State_Name","District_Name"]].drop_duplicates()

      State_Name       District_Name
27005      Bihar              ARARIA
27571      Bihar               ARWAL
27868      Bihar          AURANGABAD
28315      Bihar               BANKA
28752      Bihar           BEGUSARAI
29342      Bihar           BHAGALPUR
29953      Bihar             BHOJPUR
30450      Bihar               BUXAR
30863      Bihar           DARBHANGA
31363      Bihar                GAYA
31939      Bihar           GOPALGANJ
32462      Bihar               JAMUI
32840      Bihar           JEHANABAD
33318      Bihar     KAIMUR (BHABUA)
33721      Bihar             KATIHAR
34300      Bihar            KHAGARIA
34878      Bihar          KISHANGANJ
35427      Bihar          LAKHISARAI
35702      Bihar           MADHEPURA
36241      Bihar           MADHUBANI
36828      Bihar              MUNGER
37236      Bihar         MUZAFFARPUR
37790      Bihar             NALANDA
38250      Bihar              NAWADA
38768      Bihar  PASHCHIM CHAMPARAN
39342      Bihar               PATNA
39795      Bihar     PURBI CHAMPARAN
40345      Bihar              PURNIA
40891      Bihar              ROHTAS
41389      Bihar             SAHARSA
41894      Bihar          SAMASTIPUR
42471      Bihar               SARAN
42977      Bihar          SHEIKHPURA
43274      Bihar             SHEOHAR
43691      Bihar           SITAMARHI
44221      Bihar               SIWAN
44772      Bihar              SUPAUL
45318      Bihar            VAISHALI